### ISSUE TITLE
Cant build on windows

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/CSDP.jl#50] opened 2019-11-17 23:43 UTC
CSDP is not building on windows. Is this related to #5 ?

```
(bilevel) pkg> build CSDP
  Building CSDP → `C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT\deps\build.log`
┌ Error: Error building `CSDP`:
│ WARNING: redefining constant depends
│ [ Info: Using the blas and lapack libraries shipped with Julia as there is no system blas and lapack libraries installed.
│ [ Info: Attempting to create directory C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT\deps\downloads
│ [ Info: Directory C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT\deps\downloads already exists
│ [ Info: Downloading file https://github.com/EQt/winlapack/blob/49454aee32649dc52c5b64f408a17b5270bd30f4/win-csdp-64.7z?raw=true
│ [ Info: Done downloading file https://github.com/EQt/winlapack/blob/49454aee32649dc52c5b64f408a17b5270bd30f4/win-csdp-64.7z?raw=true
│ [ Info: Attempting to create directory C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT
│ [ Info: Directory C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT already exists
│ [ Info: Path C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT\deps\usr already exists
│ ERROR: LoadError: Provider Binaries failed to satisfy dependency csdp
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\joaquimgarcia\.julia\packages\BinDeps\ZEval\src\dependencies.jl:945
│  [3] satisfy!(::BinDeps.LibraryDependency) at C:\Users\joaquimgarcia\.julia\packages\BinDeps\ZEval\src\dependencies.jl:922
│  [4] top-level scope at C:\Users\joaquimgarcia\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [5] include at .\boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at .\loading.jl:1044
│  [7] include(::Module, ::String) at .\sysimg.jl:29
│  [8] include(::String) at .\client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at C:\Users\joaquimgarcia\.julia\packages\CSDP\VXVsT\deps\build.jl:80
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1096

(bilevel) pkg> st
    Status `C:\Users\joaquimgarcia\AppData\Local\Julia-1.0.4\bilevel\Project.toml`
  [2a10ce0d] BilevelJuMP v0.1.0 [`C:\Users\joaquimgarcia\.julia\dev\BilevelJuMP`]
  [0a46da34] CSDP v0.5.2
  [191a621a] Dualization v0.2.0 [`C:\Users\joaquimgarcia\.julia\dev\Dualization`]
  [60bf3e95] GLPK v0.11.4
  [2e9cd046] Gurobi v0.7.2
  [b6b21f68] Ipopt v0.6.0
  [4076af6c] JuMP v0.20.0
  [f4570300] MathOptFormat v0.2.2
  [b8f27783] MathOptInterface v0.9.5
```

**Comment by blegat** [comment] 2019-11-18 08:46
> CSDP is not building on windows.

I can see it fails on AppVeyor but I have no idea what's the issue. Help is welcome :)
One way to fix it might be to use BinaryBuilder but there might be an easy fix with BinDeps as it used to be working.
The issue is that even if we get the build process to succeed in Windows, the DLLs that are downloaded are outdated as we now use https://github.com/coin-or/Csdp/pull/12 

> Is this related to #5 ?

https://github.com/JuliaOpt/CSDP.jl/issues/5 was fixed but we forgot to close it.

**Closed as completed** 2020-05-02 14:48 UTC
